version: '3'

services:
  web_db:
    image: postgres:12.2
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - smart-theater
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

  web_api:
    build: .
    command: /dist/smart
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - smart-theater
    depends_on:
      - web_db
    volumes:
      - .:/code
      - ./volumes/backend/media:/code/media
      - ./volumes/backend/static:/code/static
      - ./volumes/log:/var/log

networks:
  smart-theater:
    name: smart-theater
