version: '3'

services:
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

  web:
    image: shumoff/smart-theater:latest
    command: /dist/smart
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./volumes/backend/media:/code/media
      - ./volumes/backend/static:/code/static
      - ./volumes/log:/var/log
