// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuffs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecommenderClient is the client API for Recommender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommenderClient interface {
	RecommendMovie(ctx context.Context, in *RelevantMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	RecommendSimilarMovie(ctx context.Context, in *SimilarMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	RecommendRelevantSimilarMovie(ctx context.Context, in *RelevantSimilarMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
}

type recommenderClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommenderClient(cc grpc.ClientConnInterface) RecommenderClient {
	return &recommenderClient{cc}
}

func (c *recommenderClient) RecommendMovie(ctx context.Context, in *RelevantMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, "/Recommender/RecommendMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderClient) RecommendSimilarMovie(ctx context.Context, in *SimilarMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, "/Recommender/RecommendSimilarMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderClient) RecommendRelevantSimilarMovie(ctx context.Context, in *RelevantSimilarMovieRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, "/Recommender/RecommendRelevantSimilarMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommenderServer is the server API for Recommender service.
// All implementations must embed UnimplementedRecommenderServer
// for forward compatibility
type RecommenderServer interface {
	RecommendMovie(context.Context, *RelevantMovieRequest) (*RecommendationResponse, error)
	RecommendSimilarMovie(context.Context, *SimilarMovieRequest) (*RecommendationResponse, error)
	RecommendRelevantSimilarMovie(context.Context, *RelevantSimilarMovieRequest) (*RecommendationResponse, error)
	mustEmbedUnimplementedRecommenderServer()
}

// UnimplementedRecommenderServer must be embedded to have forward compatible implementations.
type UnimplementedRecommenderServer struct {
}

func (UnimplementedRecommenderServer) RecommendMovie(context.Context, *RelevantMovieRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendMovie not implemented")
}
func (UnimplementedRecommenderServer) RecommendSimilarMovie(context.Context, *SimilarMovieRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendSimilarMovie not implemented")
}
func (UnimplementedRecommenderServer) RecommendRelevantSimilarMovie(context.Context, *RelevantSimilarMovieRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendRelevantSimilarMovie not implemented")
}
func (UnimplementedRecommenderServer) mustEmbedUnimplementedRecommenderServer() {}

// UnsafeRecommenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommenderServer will
// result in compilation errors.
type UnsafeRecommenderServer interface {
	mustEmbedUnimplementedRecommenderServer()
}

func RegisterRecommenderServer(s grpc.ServiceRegistrar, srv RecommenderServer) {
	s.RegisterService(&Recommender_ServiceDesc, srv)
}

func _Recommender_RecommendMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelevantMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServer).RecommendMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Recommender/RecommendMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServer).RecommendMovie(ctx, req.(*RelevantMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recommender_RecommendSimilarMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServer).RecommendSimilarMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Recommender/RecommendSimilarMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServer).RecommendSimilarMovie(ctx, req.(*SimilarMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recommender_RecommendRelevantSimilarMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelevantSimilarMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServer).RecommendRelevantSimilarMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Recommender/RecommendRelevantSimilarMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServer).RecommendRelevantSimilarMovie(ctx, req.(*RelevantSimilarMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recommender_ServiceDesc is the grpc.ServiceDesc for Recommender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recommender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recommender",
	HandlerType: (*RecommenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendMovie",
			Handler:    _Recommender_RecommendMovie_Handler,
		},
		{
			MethodName: "RecommendSimilarMovie",
			Handler:    _Recommender_RecommendSimilarMovie_Handler,
		},
		{
			MethodName: "RecommendRelevantSimilarMovie",
			Handler:    _Recommender_RecommendRelevantSimilarMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuffs/recommender.proto",
}
